[2025-04-12 18:18:00,146] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-12 18:18:00,228] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-12 20:25:18,718] - [aiogram.dispatcher] - [ERROR]: Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 1236] Подключение к сети было разорвано локальной системой
[2025-04-12 20:25:18,719] - [aiogram.dispatcher] - [WARNING]: Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 7527441182)
[2025-04-13 08:26:11,057] - [aiogram.dispatcher] - [ERROR]: Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
[2025-04-13 08:26:16,377] - [aiogram.dispatcher] - [WARNING]: Sleep for 1.515784 seconds and try again... (tryings = 1, bot id = 7527441182)
[2025-04-13 08:26:28,066] - [aiogram.dispatcher] - [INFO]: Connection established (tryings = 2, bot id = 7527441182)
[2025-04-13 10:48:52,382] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 10:48:52,459] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 10:49:08,101] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 10:49:08,463] - [aiogram.event] - [INFO]: Update id=112029872 is handled. Duration 953 ms by bot id=7527441182
[2025-04-13 10:49:13,845] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 105
[2025-04-13 10:49:13,985] - [aiogram.event] - [INFO]: Update id=112029873 is handled. Duration 218 ms by bot id=7527441182
[2025-04-13 10:50:28,989] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 10:50:29,055] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 10:57:20,529] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 10:57:20,700] - [aiogram.event] - [INFO]: Update id=112029874 is handled. Duration 734 ms by bot id=7527441182
[2025-04-13 10:57:22,378] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 105
[2025-04-13 10:57:22,512] - [aiogram.event] - [INFO]: Update id=112029875 is handled. Duration 203 ms by bot id=7527441182
[2025-04-13 10:57:31,099] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 192
[2025-04-13 10:57:31,185] - [aiogram.event] - [INFO]: Update id=112029876 is handled. Duration 187 ms by bot id=7527441182
[2025-04-13 10:57:49,046] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 220
[2025-04-13 11:05:00,931] - [database] - [ERROR]: Request execute was failed. Reason: ОШИБКА:  ошибка синтаксиса (примерное положение: "', '")
LINE 1: ...from Repair_Request)+1, 956847261, 'quuizhqo', 305', 'Не зап...
                                                             ^

[2025-04-13 11:05:04,752] - [aiogram.dispatcher] - [ERROR]: Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
[2025-04-13 11:05:04,753] - [aiogram.dispatcher] - [WARNING]: Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 7527441182)
[2025-04-13 11:05:04,917] - [aiogram.event] - [INFO]: Update id=112029877 is handled. Duration 436030 ms by bot id=7527441182
[2025-04-13 11:05:15,807] - [aiogram.dispatcher] - [INFO]: Connection established (tryings = 1, bot id = 7527441182)
[2025-04-13 11:08:44,953] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 11:08:45,038] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 11:08:54,751] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 11:08:54,888] - [aiogram.event] - [INFO]: Update id=112029878 is handled. Duration 625 ms by bot id=7527441182
[2025-04-13 11:09:30,858] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 105
[2025-04-13 11:09:31,021] - [aiogram.event] - [INFO]: Update id=112029879 is handled. Duration 375 ms by bot id=7527441182
[2025-04-13 11:11:30,906] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 192
[2025-04-13 11:11:31,089] - [aiogram.event] - [INFO]: Update id=112029880 is handled. Duration 359 ms by bot id=7527441182
[2025-04-13 11:11:33,036] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 220
[2025-04-13 11:11:37,682] - [database] - [ERROR]: Request execute was failed. Reason: ОШИБКА:  ошибка синтаксиса (примерное положение: "', '")
LINE 1: ...from Repair_Request)+1, 956847261, 'quuizhqo', 306', 'asd', ...
                                                             ^

[2025-04-13 11:11:37,684] - [bot_main] - [ERROR]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 235 | Text: Request execute was failed
[2025-04-13 11:11:51,766] - [aiogram.event] - [INFO]: Update id=112029881 is handled. Duration 18781 ms by bot id=7527441182
[2025-04-13 11:11:55,298] - [database] - [ERROR]: Request execute was failed. Reason: ОШИБКА:  текущая транзакция прервана, команды до конца блока транзакции игнорируются

[2025-04-13 11:11:55,299] - [aiogram.event] - [INFO]: Update id=112029882 is not handled. Duration 0 ms by bot id=7527441182
[2025-04-13 11:11:55,299] - [aiogram.event] - [ERROR]: Cause exception while process update id=112029882 by bot id=7527441182
Exception: Request execute was failed
Traceback (most recent call last):
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\utilits\bd.py", line 31, in reqExecute
    cursor.execute(request)
psycopg2.errors.InFailedSqlTransaction: ОШИБКА:  текущая транзакция прервана, команды до конца блока транзакции игнорируются


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 161, in _propagate_event
    result, data = await observer.check_root_filters(event, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 94, in check
    check = await event_filter.call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\filters.py", line 17, in __call__
    result=bd.reqExecute("Select TG_ID from Users")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\utilits\bd.py", line 44, in reqExecute
    raise Exception("Request execute was failed")
Exception: Request execute was failed
[2025-04-13 11:12:14,732] - [database] - [ERROR]: Request execute was failed. Reason: ОШИБКА:  текущая транзакция прервана, команды до конца блока транзакции игнорируются

[2025-04-13 11:12:14,733] - [aiogram.event] - [INFO]: Update id=112029883 is not handled. Duration 0 ms by bot id=7527441182
[2025-04-13 11:12:14,733] - [aiogram.event] - [ERROR]: Cause exception while process update id=112029883 by bot id=7527441182
Exception: Request execute was failed
Traceback (most recent call last):
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\utilits\bd.py", line 31, in reqExecute
    cursor.execute(request)
psycopg2.errors.InFailedSqlTransaction: ОШИБКА:  текущая транзакция прервана, команды до конца блока транзакции игнорируются


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 161, in _propagate_event
    result, data = await observer.check_root_filters(event, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 94, in check
    check = await event_filter.call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\filters.py", line 17, in __call__
    result=bd.reqExecute("Select TG_ID from Users")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\utilits\bd.py", line 44, in reqExecute
    raise Exception("Request execute was failed")
Exception: Request execute was failed
[2025-04-13 11:19:12,126] - [database] - [ERROR]: Request execute was failed. Reason: ОШИБКА:  текущая транзакция прервана, команды до конца блока транзакции игнорируются

[2025-04-13 11:19:12,127] - [aiogram.event] - [INFO]: Update id=112029884 is not handled. Duration 0 ms by bot id=7527441182
[2025-04-13 11:19:12,127] - [aiogram.event] - [ERROR]: Cause exception while process update id=112029884 by bot id=7527441182
Exception: Request execute was failed
Traceback (most recent call last):
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\utilits\bd.py", line 31, in reqExecute
    cursor.execute(request)
psycopg2.errors.InFailedSqlTransaction: ОШИБКА:  текущая транзакция прервана, команды до конца блока транзакции игнорируются


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 161, in _propagate_event
    result, data = await observer.check_root_filters(event, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 94, in check
    check = await event_filter.call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\filters.py", line 17, in __call__
    result=bd.reqExecute("Select TG_ID from Users")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\utilits\bd.py", line 44, in reqExecute
    raise Exception("Request execute was failed")
Exception: Request execute was failed
[2025-04-13 11:22:22,517] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 11:22:22,581] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 11:22:30,234] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 11:22:30,376] - [aiogram.event] - [INFO]: Update id=112029885 is handled. Duration 625 ms by bot id=7527441182
[2025-04-13 11:22:33,984] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 105
[2025-04-13 11:22:34,145] - [aiogram.event] - [INFO]: Update id=112029886 is handled. Duration 219 ms by bot id=7527441182
[2025-04-13 11:22:35,718] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 192
[2025-04-13 11:22:35,814] - [aiogram.event] - [INFO]: Update id=112029887 is handled. Duration 171 ms by bot id=7527441182
[2025-04-13 11:22:37,551] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 220
[2025-04-13 11:22:40,727] - [database] - [ERROR]: Request execute was failed. Reason: ОШИБКА:  ошибка синтаксиса (примерное положение: "', '")
LINE 1: ...from Repair_Request)+1, 956847261, 'quuizhqo', 305', 'asd', ...
                                                             ^

[2025-04-13 11:22:40,729] - [bot_main] - [ERROR]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 235 | Text: Request execute was failed
[2025-04-13 11:25:02,486] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 11:25:02,560] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 11:25:19,964] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 11:25:22,708] - [aiogram.event] - [INFO]: Update id=112029889 is handled. Duration 12562 ms by bot id=7527441182
[2025-04-13 11:25:27,823] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 105
[2025-04-13 11:25:28,109] - [aiogram.event] - [INFO]: Update id=112029890 is handled. Duration 3155 ms by bot id=7527441182
[2025-04-13 11:42:05,910] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 11:42:05,972] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 11:46:35,231] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 11:46:36,854] - [aiogram.event] - [INFO]: Update id=112029892 is handled. Duration 6452 ms by bot id=7527441182
[2025-04-13 11:46:40,290] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 105
[2025-04-13 11:46:40,425] - [aiogram.event] - [INFO]: Update id=112029893 is handled. Duration 202 ms by bot id=7527441182
[2025-04-13 11:46:46,098] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 192
[2025-04-13 11:46:46,255] - [aiogram.event] - [INFO]: Update id=112029894 is handled. Duration 233 ms by bot id=7527441182
[2025-04-13 11:46:54,945] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 76
[2025-04-13 11:47:01,815] - [aiogram.event] - [INFO]: Update id=112029895 is handled. Duration 10421 ms by bot id=7527441182
[2025-04-13 11:47:33,763] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 11:47:33,830] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 11:47:47,394] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 11:47:47,596] - [aiogram.event] - [INFO]: Update id=112029896 is handled. Duration 719 ms by bot id=7527441182
[2025-04-13 11:47:48,687] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 105
[2025-04-13 11:47:48,821] - [aiogram.event] - [INFO]: Update id=112029897 is handled. Duration 203 ms by bot id=7527441182
[2025-04-13 11:47:51,526] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 192
[2025-04-13 11:47:51,691] - [aiogram.event] - [INFO]: Update id=112029898 is handled. Duration 233 ms by bot id=7527441182
[2025-04-13 11:47:55,735] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 76
[2025-04-13 11:47:57,199] - [aiogram.event] - [INFO]: Update id=112029899 is handled. Duration 3312 ms by bot id=7527441182
[2025-04-13 11:48:03,267] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 105
[2025-04-13 11:48:03,345] - [aiogram.event] - [INFO]: Update id=112029900 is handled. Duration 140 ms by bot id=7527441182
[2025-04-13 11:48:08,204] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 192
[2025-04-13 11:48:08,281] - [aiogram.event] - [INFO]: Update id=112029901 is handled. Duration 141 ms by bot id=7527441182
[2025-04-13 11:48:13,600] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 220
[2025-04-13 11:48:58,857] - [database] - [ERROR]: Request execute was failed. Reason: ОШИБКА:  ошибка синтаксиса (примерное положение: "', '")
LINE 1: ...from Repair_Request)+1, 956847261, 'quuizhqo', 207', 'asd', ...
                                                             ^

[2025-04-13 11:48:58,860] - [bot_main] - [ERROR]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 235 | Text: Request execute was failed
[2025-04-13 11:49:00,706] - [aiogram.event] - [INFO]: Update id=112029902 is handled. Duration 47171 ms by bot id=7527441182
[2025-04-13 11:49:20,288] - [database] - [ERROR]: Request execute was failed. Reason: ОШИБКА:  текущая транзакция прервана, команды до конца блока транзакции игнорируются

[2025-04-13 11:49:20,288] - [aiogram.event] - [INFO]: Update id=112029903 is not handled. Duration 14047 ms by bot id=7527441182
[2025-04-13 11:49:20,289] - [aiogram.event] - [ERROR]: Cause exception while process update id=112029903 by bot id=7527441182
Exception: Request execute was failed
Traceback (most recent call last):
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\utilits\bd.py", line 31, in reqExecute
    cursor.execute(request)
psycopg2.errors.InFailedSqlTransaction: ОШИБКА:  текущая транзакция прервана, команды до конца блока транзакции игнорируются


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\router.py", line 161, in _propagate_event
    result, data = await observer.check_root_filters(event, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 94, in check
    check = await event_filter.call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\filters.py", line 45, in __call__
    result=bd.reqExecute("Select TG_ID from Users")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\utilits\bd.py", line 44, in reqExecute
    raise Exception("Request execute was failed")
Exception: Request execute was failed
[2025-04-13 11:50:03,739] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 11:50:03,809] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 11:50:29,172] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 11:50:29,242] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 11:50:52,343] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 11:50:52,519] - [aiogram.event] - [INFO]: Update id=112029904 is handled. Duration 687 ms by bot id=7527441182
[2025-04-13 11:50:53,413] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 105
[2025-04-13 11:50:53,567] - [aiogram.event] - [INFO]: Update id=112029905 is handled. Duration 233 ms by bot id=7527441182
[2025-04-13 11:50:55,698] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 192
[2025-04-13 11:50:55,799] - [aiogram.event] - [INFO]: Update id=112029906 is handled. Duration 171 ms by bot id=7527441182
[2025-04-13 11:51:01,258] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 220
[2025-04-13 11:52:22,261] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 11:52:22,326] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 11:52:24,351] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 11:52:24,511] - [aiogram.event] - [INFO]: Update id=112029908 is handled. Duration 625 ms by bot id=7527441182
[2025-04-13 11:52:25,662] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 105
[2025-04-13 11:52:25,867] - [aiogram.event] - [INFO]: Update id=112029909 is handled. Duration 265 ms by bot id=7527441182
[2025-04-13 11:52:26,947] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 192
[2025-04-13 11:52:27,110] - [aiogram.event] - [INFO]: Update id=112029910 is handled. Duration 218 ms by bot id=7527441182
[2025-04-13 11:52:31,035] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 192
[2025-04-13 11:52:31,205] - [aiogram.event] - [INFO]: Update id=112029911 is handled. Duration 219 ms by bot id=7527441182
[2025-04-13 11:52:32,907] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 220
[2025-04-13 11:54:23,903] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 11:54:23,974] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 11:54:25,142] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 11:54:25,350] - [aiogram.event] - [INFO]: Update id=112029913 is handled. Duration 719 ms by bot id=7527441182
[2025-04-13 11:54:26,282] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 105
[2025-04-13 11:54:26,454] - [aiogram.event] - [INFO]: Update id=112029914 is handled. Duration 250 ms by bot id=7527441182
[2025-04-13 11:54:28,574] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 192
[2025-04-13 11:54:28,684] - [aiogram.event] - [INFO]: Update id=112029915 is handled. Duration 187 ms by bot id=7527441182
[2025-04-13 11:54:30,335] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 220
[2025-04-13 11:54:38,903] - [aiogram.event] - [INFO]: Update id=112029916 is handled. Duration 8641 ms by bot id=7527441182
[2025-04-13 11:55:28,756] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 76
[2025-04-13 11:55:31,272] - [aiogram.event] - [INFO]: Update id=112029917 is handled. Duration 4687 ms by bot id=7527441182
[2025-04-13 12:06:10,534] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 12:06:10,606] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 12:07:15,572] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 12:07:15,708] - [aiogram.event] - [INFO]: Update id=112029918 is handled. Duration 641 ms by bot id=7527441182
[2025-04-13 12:07:17,051] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 105
[2025-04-13 12:07:17,177] - [aiogram.event] - [INFO]: Update id=112029919 is handled. Duration 217 ms by bot id=7527441182
[2025-04-13 12:07:19,058] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 192
[2025-04-13 12:07:19,186] - [aiogram.event] - [INFO]: Update id=112029920 is handled. Duration 203 ms by bot id=7527441182
[2025-04-13 12:07:19,885] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 220
[2025-04-13 12:07:45,544] - [aiogram.event] - [INFO]: Update id=112029921 is handled. Duration 25717 ms by bot id=7527441182
[2025-04-13 12:08:33,752] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 76
[2025-04-13 12:08:35,589] - [aiogram.event] - [INFO]: Update id=112029922 is handled. Duration 4234 ms by bot id=7527441182
[2025-04-13 12:09:06,546] - [aiogram.event] - [INFO]: Update id=112029923 is not handled. Duration 171 ms by bot id=7527441182
[2025-04-13 12:26:54,358] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 12:26:54,428] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 12:27:32,081] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 12:27:32,318] - [aiogram.event] - [INFO]: Update id=112029924 is handled. Duration 718 ms by bot id=7527441182
[2025-04-13 12:27:33,524] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 125
[2025-04-13 12:28:01,605] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 12:28:01,663] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 12:28:03,283] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 12:28:03,423] - [aiogram.event] - [INFO]: Update id=112029927 is handled. Duration 592 ms by bot id=7527441182
[2025-04-13 12:28:04,604] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 125
[2025-04-13 12:28:06,183] - [aiogram.event] - [INFO]: Update id=112029928 is handled. Duration 1718 ms by bot id=7527441182
[2025-04-13 12:28:17,292] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 143
[2025-04-13 12:28:26,314] - [aiogram.event] - [INFO]: Update id=112029929 is handled. Duration 9125 ms by bot id=7527441182
[2025-04-13 12:28:40,920] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 76
[2025-04-13 12:28:45,832] - [aiogram.event] - [INFO]: Update id=112029930 is handled. Duration 8203 ms by bot id=7527441182
[2025-04-13 12:32:35,616] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 12:32:35,701] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 12:33:26,080] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 12:33:26,143] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 12:33:31,170] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 12:33:31,307] - [aiogram.event] - [INFO]: Update id=112029932 is handled. Duration 625 ms by bot id=7527441182
[2025-04-13 12:33:32,915] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 129
[2025-04-13 12:33:35,328] - [aiogram.event] - [INFO]: Update id=112029933 is handled. Duration 2484 ms by bot id=7527441182
[2025-04-13 12:33:37,553] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 146
[2025-04-13 12:34:37,741] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 12:34:37,805] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 12:34:43,506] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 12:34:43,649] - [aiogram.event] - [INFO]: Update id=112029935 is handled. Duration 687 ms by bot id=7527441182
[2025-04-13 12:34:49,096] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 129
[2025-04-13 12:34:49,215] - [aiogram.event] - [INFO]: Update id=112029936 is handled. Duration 203 ms by bot id=7527441182
[2025-04-13 12:34:52,036] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 146
[2025-04-13 12:36:00,717] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 12:36:00,792] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 12:36:20,616] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 12:36:20,766] - [aiogram.event] - [INFO]: Update id=112029938 is handled. Duration 733 ms by bot id=7527441182
[2025-04-13 12:36:22,023] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 129
[2025-04-13 12:36:22,226] - [aiogram.event] - [INFO]: Update id=112029939 is handled. Duration 297 ms by bot id=7527441182
[2025-04-13 12:36:23,264] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 146
[2025-04-13 12:37:09,879] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 12:37:09,937] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 12:37:18,010] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 12:37:18,154] - [aiogram.event] - [INFO]: Update id=112029941 is handled. Duration 641 ms by bot id=7527441182
[2025-04-13 12:37:20,781] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 129
[2025-04-13 12:37:20,914] - [aiogram.event] - [INFO]: Update id=112029942 is handled. Duration 203 ms by bot id=7527441182
[2025-04-13 12:37:21,830] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 146
[2025-04-13 12:37:24,237] - [aiogram.event] - [INFO]: Update id=112029943 is handled. Duration 2484 ms by bot id=7527441182
[2025-04-13 12:37:32,964] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 76
[2025-04-13 12:37:34,667] - [aiogram.event] - [INFO]: Update id=112029944 is handled. Duration 8000 ms by bot id=7527441182
[2025-04-13 12:37:43,900] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 129
[2025-04-13 12:37:43,990] - [aiogram.event] - [INFO]: Update id=112029945 is handled. Duration 155 ms by bot id=7527441182
[2025-04-13 12:37:44,751] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 146
[2025-04-13 12:38:59,982] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 12:39:00,043] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 12:39:10,227] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 12:39:10,393] - [aiogram.event] - [INFO]: Update id=112029947 is handled. Duration 687 ms by bot id=7527441182
[2025-04-13 12:39:11,370] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 129
[2025-04-13 12:39:11,674] - [aiogram.event] - [INFO]: Update id=112029948 is handled. Duration 375 ms by bot id=7527441182
[2025-04-13 12:39:12,659] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 146
[2025-04-13 12:39:58,530] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 12:39:58,588] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 12:40:05,984] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 12:40:06,140] - [aiogram.event] - [INFO]: Update id=112029950 is handled. Duration 781 ms by bot id=7527441182
[2025-04-13 12:40:07,148] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 129
[2025-04-13 12:40:07,366] - [aiogram.event] - [INFO]: Update id=112029951 is handled. Duration 312 ms by bot id=7527441182
[2025-04-13 12:40:10,238] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 146
[2025-04-13 12:41:52,624] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 12:41:52,690] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 12:41:53,463] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 12:41:53,598] - [aiogram.event] - [INFO]: Update id=112029953 is handled. Duration 672 ms by bot id=7527441182
[2025-04-13 12:41:54,469] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 129
[2025-04-13 12:41:54,629] - [aiogram.event] - [INFO]: Update id=112029954 is handled. Duration 217 ms by bot id=7527441182
[2025-04-13 12:41:55,981] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 146
[2025-04-13 12:42:12,036] - [aiogram.event] - [INFO]: Update id=112029955 is handled. Duration 16125 ms by bot id=7527441182
[2025-04-13 12:42:16,388] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 76
[2025-04-13 12:42:19,386] - [aiogram.event] - [INFO]: Update id=112029956 is handled. Duration 5281 ms by bot id=7527441182
[2025-04-13 12:44:18,560] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 12:44:18,623] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 12:44:22,945] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 12:44:23,101] - [aiogram.event] - [INFO]: Update id=112029957 is handled. Duration 640 ms by bot id=7527441182
[2025-04-13 12:44:24,297] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 129
[2025-04-13 12:44:24,437] - [aiogram.event] - [INFO]: Update id=112029958 is handled. Duration 218 ms by bot id=7527441182
[2025-04-13 12:44:25,933] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 146
[2025-04-13 12:44:33,840] - [aiogram.event] - [INFO]: Update id=112029959 is handled. Duration 8000 ms by bot id=7527441182
[2025-04-13 12:44:47,236] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 76
[2025-04-13 12:44:47,464] - [aiogram.event] - [INFO]: Update id=112029960 is handled. Duration 10172 ms by bot id=7527441182
[2025-04-13 12:45:25,487] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 12:45:25,564] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 12:46:16,953] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 12:46:17,206] - [aiogram.event] - [INFO]: Update id=112029961 is handled. Duration 766 ms by bot id=7527441182
[2025-04-13 12:46:18,180] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 129
[2025-04-13 12:46:18,347] - [aiogram.event] - [INFO]: Update id=112029962 is handled. Duration 234 ms by bot id=7527441182
[2025-04-13 12:46:18,921] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 76
[2025-04-13 12:46:18,996] - [aiogram.event] - [INFO]: Update id=112029963 is handled. Duration 155 ms by bot id=7527441182
[2025-04-13 12:46:24,698] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 129
[2025-04-13 12:46:24,775] - [aiogram.event] - [INFO]: Update id=112029964 is handled. Duration 125 ms by bot id=7527441182
[2025-04-13 12:46:26,353] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 76
[2025-04-13 12:46:26,432] - [aiogram.event] - [INFO]: Update id=112029965 is handled. Duration 141 ms by bot id=7527441182
[2025-04-13 12:46:27,005] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 109
[2025-04-13 12:46:27,082] - [aiogram.event] - [INFO]: Update id=112029966 is handled. Duration 125 ms by bot id=7527441182
[2025-04-13 12:47:07,964] - [aiogram.dispatcher] - [INFO]: Start polling
[2025-04-13 12:47:08,029] - [aiogram.dispatcher] - [INFO]: Run polling for bot @HAMT_Tech_Bot id=7527441182 - 'Техническая поддержка ГБПОУ "НАМТ"'
[2025-04-13 12:47:30,798] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 30
[2025-04-13 12:47:30,976] - [aiogram.event] - [INFO]: Update id=112029967 is handled. Duration 703 ms by bot id=7527441182
[2025-04-13 12:47:32,019] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 129
[2025-04-13 12:47:32,199] - [aiogram.event] - [INFO]: Update id=112029968 is handled. Duration 266 ms by bot id=7527441182
[2025-04-13 12:47:32,716] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 76
[2025-04-13 12:47:32,853] - [aiogram.event] - [INFO]: Update id=112029969 is handled. Duration 218 ms by bot id=7527441182
[2025-04-13 12:47:33,438] - [bot_main] - [INFO]:  UserID/Username: 956847261/quuizhqo | Event: E:\PROJECT\Python\NAMT_BOT\Git\UnimportantProject_HAMT\Bot\userHandlers.py | Line: 109
[2025-04-13 12:47:33,628] - [aiogram.event] - [INFO]: Update id=112029970 is handled. Duration 250 ms by bot id=7527441182
